import type { Locale } from "./locale";

const shared = {
  date: "2026-10-30",
  href: "/news/vertrauen-das-bleibt",
  image: "/news/vertrauen-das-bleibt/3.jpeg",
};

const copy = {
  "de": {
    "titleFirst": "Vertrauen,",
    "titleSecond": "das bleibt.",
    "intro": "Auf der Interboot in Friedrichshafen haben wir gemeinsam mit dem DLRG Landesverband Baden den Vertrag für eine zweite Tinn-Silver am Bodensee unterzeichnet: ein 11 Meter langes Boot für die DLRG Ortsgruppe Konstanz.",
    "thanks": "Herzlichen Dank an alle Beteiligten für das Vertrauen in unser Team und unsere Boote!",
    "subtitle": "Gemeinsam mit der DLRG. Für den Bodensee.",
    "heroCaption": "Ein gemeinsamer Schritt für die Wasserrettung am Bodensee.",
    "storyLabel": "Eine zweite Tinn-Silver am Bodensee",
    "metres": "Meter",
    "recipient": "Für die DLRG Ortsgruppe Konstanz",
    "galleryLabel": "Die Partnerschaft in Bildern",
    "galleryFirst": "Ein Handschlag.",
    "gallerySecond": "Ein gemeinsamer Kurs.",
    "signingCaption": "Vertrauen wird zur Zusammenarbeit.",
    "boatCaption": "Tinn-Silver für die Wasserrettung.",
    "allNews": "Alle News ansehen",
    "back": "Zurück zu News",
    "readMore": "Mehr erfahren",
    "role": "Geschäftsführer,",
    "location": "Interboot · Friedrichshafen",
    "journal": "Tinn Silver Journal",
    "heroAlt": "Gruppenfoto mit Handschlag am Tinn-Silver-Messestand auf der Interboot",
    "signingAlt": "Gemeinsame Vertragsunterzeichnung am Tisch auf der Interboot",
    "personAlt": "Jan Tinnemans bei der Unterzeichnung des Vertrags",
    "boatAlt": "Rotes DLRG-Wasserrettungsboot auf einem Transportwagen an der Werft"
  },
  "en": {
    "titleFirst": "Trust",
    "titleSecond": "that lasts.",
    "intro": "At Interboot in Friedrichshafen, together with the DLRG regional association of Baden, we signed the contract for a second Tinn-Silver on Lake Konstanz: an 11-metre boat for the DLRG local branch in Konstanz.",
    "thanks": "Our heartfelt thanks to everyone involved for their trust in our team and our boats!",
    "subtitle": "Together with the DLRG. For Lake Konstanz.",
    "heroCaption": "A shared step forward for water rescue on Lake Konstanz.",
    "storyLabel": "A second Tinn-Silver on Lake Konstanz",
    "metres": "metres",
    "recipient": "For the DLRG local branch in Konstanz",
    "galleryLabel": "Our partnership in pictures",
    "galleryFirst": "One handshake.",
    "gallerySecond": "One shared course.",
    "signingCaption": "Trust becomes collaboration.",
    "boatCaption": "Tinn-Silver for water rescue.",
    "allNews": "View all news",
    "back": "Back to news",
    "readMore": "Read more",
    "role": "Chief Executive Officer,",
    "location": "Interboot · Friedrichshafen",
    "journal": "Tinn Silver Journal",
    "heroAlt": "Group photo with a handshake at the Tinn-Silver stand at Interboot",
    "signingAlt": "Signing the contract together at a table at Interboot",
    "personAlt": "Jan Tinnemans signing the contract",
    "boatAlt": "Red DLRG rescue boat on a transport trailer at the shipyard"
  },
  "nl": {
    "titleFirst": "Vertrouwen",
    "titleSecond": "dat blijft.",
    "intro": "Op de Interboot in Friedrichshafen hebben we samen met de DLRG Landesverband Baden het contract ondertekend voor een tweede Tinn-Silver op het Bodenmeer: een boot van 11 meter voor de lokale DLRG-afdeling Konstanz.",
    "thanks": "Hartelijk dank aan alle betrokkenen voor het vertrouwen in ons team en onze boten!",
    "subtitle": "Samen met de DLRG. Voor het Bodenmeer.",
    "heroCaption": "Een gezamenlijke stap voor de waterredding op het Bodenmeer.",
    "storyLabel": "Een tweede Tinn-Silver op het Bodenmeer",
    "metres": "meter",
    "recipient": "Voor de lokale DLRG-afdeling Konstanz",
    "galleryLabel": "De samenwerking in beeld",
    "galleryFirst": "Een handdruk.",
    "gallerySecond": "Een gezamenlijke koers.",
    "signingCaption": "Vertrouwen wordt samenwerking.",
    "boatCaption": "Tinn-Silver voor waterredding.",
    "allNews": "Bekijk alle nieuwsberichten",
    "back": "Terug naar nieuws",
    "readMore": "Lees meer",
    "role": "Algemeen directeur,",
    "location": "Interboot · Friedrichshafen",
    "journal": "Tinn Silver Journaal",
    "heroAlt": "Groepsfoto met een handdruk op de Tinn-Silver-stand tijdens de Interboot",
    "signingAlt": "Gezamenlijke ondertekening van het contract aan tafel op de Interboot",
    "personAlt": "Jan Tinnemans ondertekent het contract",
    "boatAlt": "Rode DLRG-reddingsboot op een transportwagen bij de werf"
  },
  "ar": {
    "titleFirst": "ثقة",
    "titleSecond": "تدوم.",
    "intro": "في معرض إنتربوت في فريدريشهافن، وقّعنا بالتعاون مع الاتحاد الإقليمي لمنظمة DLRG في بادن عقدًا لقارب Tinn-Silver ثانٍ على بحيرة Konstanz: قارب بطول 11 مترًا لفرع DLRG المحلي في Konstanz.",
    "thanks": "جزيل الشكر لجميع المشاركين على ثقتهم بفريقنا وقواربنا!",
    "subtitle": "مع DLRG. من أجل بحيرة Konstanz.",
    "heroCaption": "خطوة مشتركة لدعم الإنقاذ المائي على بحيرة Konstanz.",
    "storyLabel": "قارب Tinn-Silver ثانٍ على بحيرة Konstanz",
    "metres": "مترًا",
    "recipient": "لفرع DLRG المحلي في Konstanz",
    "galleryLabel": "شراكتنا بالصور",
    "galleryFirst": "مصافحة واحدة.",
    "gallerySecond": "ومسار مشترك.",
    "signingCaption": "الثقة تتحول إلى تعاون.",
    "boatCaption": "Tinn-Silver للإنقاذ المائي.",
    "allNews": "عرض جميع الأخبار",
    "back": "العودة إلى الأخبار",
    "readMore": "اقرأ المزيد",
    "role": "الرئيس التنفيذي،",
    "location": "إنتربوت · فريدريشهافن",
    "journal": "مجلة Tinn Silver",
    "heroAlt": "صورة جماعية مع مصافحة في جناح Tinn-Silver بمعرض إنتربوت",
    "signingAlt": "توقيع العقد معًا على طاولة في معرض إنتربوت",
    "personAlt": "يان تينيمانز أثناء توقيع العقد",
    "boatAlt": "قارب إنقاذ أحمر تابع لمنظمة DLRG على عربة نقل في حوض بناء السفن"
  }
} satisfies Record<Locale, Record<string, string>>;

export function getTrustNews(locale: Locale) {
  const text = copy[locale];
  return { ...shared, ...text, title: `${text.titleFirst} ${text.titleSecond}` };
}
